<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Xproduk;
use App\Models\Xpropinsi;
use App\Models\Xkabupaten;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Admin User',
            'email' => 'admin@erkaxpress.com',
            'password' => 'admin'
        ]);
        
        Xproduk::factory()->create([
            'code' => '1001',
            'nama' => 'Reguler'
        ]);
        
        Xpropinsi::factory()->create(['code' => '11','nama' => 'Aceh']);
        Xpropinsi::factory()->create(['code' => '12','nama' => 'Sumatera Utara']);
        Xpropinsi::factory()->create(['code' => '13','nama' => 'Sumatera Barat']);
        Xpropinsi::factory()->create(['code' => '14','nama' => 'Riau']);
        Xpropinsi::factory()->create(['code' => '15','nama' => 'Jambi']);
        Xpropinsi::factory()->create(['code' => '16','nama' => 'Sumatera Selatan']);
        Xpropinsi::factory()->create(['code' => '17','nama' => 'Bengkulu']);
        Xpropinsi::factory()->create(['code' => '18','nama' => 'Lampung']);
        Xpropinsi::factory()->create(['code' => '19','nama' => 'Kepulauan Bangka Belitung']);
        Xpropinsi::factory()->create(['code' => '21','nama' => 'Kepulauan Riau']);
        Xpropinsi::factory()->create(['code' => '31','nama' => 'DKI Jakarta']);
        Xpropinsi::factory()->create(['code' => '32','nama' => 'Jawa Barat']);
        Xpropinsi::factory()->create(['code' => '33','nama' => 'Jawa Tengah']);
        Xpropinsi::factory()->create(['code' => '34','nama' => 'Daerah Istimewa Yogyakarta']);
        Xpropinsi::factory()->create(['code' => '35','nama' => 'Jawa Timur']);
        Xpropinsi::factory()->create(['code' => '36','nama' => 'Banten']);
        Xpropinsi::factory()->create(['code' => '51','nama' => 'Bali']);
        Xpropinsi::factory()->create(['code' => '52','nama' => 'Nusa Tenggara Barat']);
        Xpropinsi::factory()->create(['code' => '53','nama' => 'Nusa Tenggara Timur']);
        Xpropinsi::factory()->create(['code' => '61','nama' => 'Kalimantan Barat']);
        Xpropinsi::factory()->create(['code' => '62','nama' => 'Kalimantan Tengah']);
        Xpropinsi::factory()->create(['code' => '63','nama' => 'Kalimantan Selatan']);
        Xpropinsi::factory()->create(['code' => '64','nama' => 'Kalimantan Timur']);
        Xpropinsi::factory()->create(['code' => '65','nama' => 'Kalimantan Utara']);
        Xpropinsi::factory()->create(['code' => '71','nama' => 'Sulawesi Utara']);
        Xpropinsi::factory()->create(['code' => '72','nama' => 'Sulawesi Tengah']);
        Xpropinsi::factory()->create(['code' => '73','nama' => 'Sulawesi Selatan']);
        Xpropinsi::factory()->create(['code' => '74','nama' => 'Sulawesi Tenggara']);
        Xpropinsi::factory()->create(['code' => '75','nama' => 'Gorontalo']);
        Xpropinsi::factory()->create(['code' => '76','nama' => 'Sulawesi Barat']);
        Xpropinsi::factory()->create(['code' => '81','nama' => 'Maluku']);
        Xpropinsi::factory()->create(['code' => '82','nama' => 'Maluku Utara']);
        Xpropinsi::factory()->create(['code' => '91','nama' => 'Papua']);
        Xpropinsi::factory()->create(['code' => '92','nama' => 'Papua Barat']);
        
        Xkabupaten::factory()->create(['code' => '1101','nama' => 'Kabupaten Aceh Selatan']);
        Xkabupaten::factory()->create(['code' => '1102','nama' => 'Kabupaten Aceh Tenggara']);
        Xkabupaten::factory()->create(['code' => '1103','nama' => 'Kabupaten Aceh Timur']);
        Xkabupaten::factory()->create(['code' => '1104','nama' => 'Kabupaten Aceh Tengah']);
        Xkabupaten::factory()->create(['code' => '1105','nama' => 'Kabupaten Aceh Barat']);
        Xkabupaten::factory()->create(['code' => '1106','nama' => 'Kabupaten Aceh Besar']);
        Xkabupaten::factory()->create(['code' => '1107','nama' => 'Kabupaten Pidie']);
        Xkabupaten::factory()->create(['code' => '1108','nama' => 'Kabupaten Aceh Utara']);
        Xkabupaten::factory()->create(['code' => '1109','nama' => 'Kabupaten Simeulue']);
        Xkabupaten::factory()->create(['code' => '1110','nama' => 'Kabupaten Aceh Singkil']);
        Xkabupaten::factory()->create(['code' => '1111','nama' => 'Kabupaten Bireuen']);
        Xkabupaten::factory()->create(['code' => '1112','nama' => 'Kabupaten Aceh Barat Daya']);
        Xkabupaten::factory()->create(['code' => '1113','nama' => 'Kabupaten Gayo Lues']);
        Xkabupaten::factory()->create(['code' => '1114','nama' => 'Kabupaten Aceh Jaya']);
        Xkabupaten::factory()->create(['code' => '1115','nama' => 'Kabupaten Nagan Raya']);
        Xkabupaten::factory()->create(['code' => '1116','nama' => 'Kabupaten Aceh Tamiang']);
        Xkabupaten::factory()->create(['code' => '1117','nama' => 'Kabupaten Bener Meriah']);
        Xkabupaten::factory()->create(['code' => '1118','nama' => 'Kabupaten Pidie Jaya']);
        Xkabupaten::factory()->create(['code' => '1171','nama' => 'Kota Banda Aceh']);
        Xkabupaten::factory()->create(['code' => '1172','nama' => 'Kota Sabang']);
        Xkabupaten::factory()->create(['code' => '1173','nama' => 'Kota Lhokseumawe']);
        Xkabupaten::factory()->create(['code' => '1174','nama' => 'Kota Langsa']);
        Xkabupaten::factory()->create(['code' => '1175','nama' => 'Kota Subulussalam']);
        Xkabupaten::factory()->create(['code' => '1201','nama' => 'Kabupaten Tapanuli Tengah']);
        Xkabupaten::factory()->create(['code' => '1202','nama' => 'Kabupaten Tapanuli Utara']);
        Xkabupaten::factory()->create(['code' => '1203','nama' => 'Kabupaten Tapanuli Selatan']);
        Xkabupaten::factory()->create(['code' => '1204','nama' => 'Kabupaten Nias']);
        Xkabupaten::factory()->create(['code' => '1205','nama' => 'Kabupaten Langkat']);
        Xkabupaten::factory()->create(['code' => '1206','nama' => 'Kabupaten Karo']);
        Xkabupaten::factory()->create(['code' => '1207','nama' => 'Kabupaten Deli Serdang']);
        Xkabupaten::factory()->create(['code' => '1208','nama' => 'Kabupaten Simalungun']);
        Xkabupaten::factory()->create(['code' => '1209','nama' => 'Kabupaten Asahan']);
        Xkabupaten::factory()->create(['code' => '1210','nama' => 'Kabupaten Labuhanbatu']);
        Xkabupaten::factory()->create(['code' => '1211','nama' => 'Kabupaten Dairi']);
        Xkabupaten::factory()->create(['code' => '1212','nama' => 'Kabupaten Toba Samosir']);
        Xkabupaten::factory()->create(['code' => '1213','nama' => 'Kabupaten Mandailing Natal']);
        Xkabupaten::factory()->create(['code' => '1214','nama' => 'Kabupaten Nias Selatan']);
        Xkabupaten::factory()->create(['code' => '1215','nama' => 'Kabupaten Pakpak Bharat']);
        Xkabupaten::factory()->create(['code' => '1216','nama' => 'Kabupaten Humbang Hasundutan']);
        Xkabupaten::factory()->create(['code' => '1217','nama' => 'Kabupaten Samosir']);
        Xkabupaten::factory()->create(['code' => '1218','nama' => 'Kabupaten Serdang Bedagai']);
        Xkabupaten::factory()->create(['code' => '1219','nama' => 'Kabupaten Batu Bara']);
        Xkabupaten::factory()->create(['code' => '1220','nama' => 'Kabupaten Padang Lawas Utara']);
        Xkabupaten::factory()->create(['code' => '1221','nama' => 'Kabupaten Padang Lawas']);
        Xkabupaten::factory()->create(['code' => '1222','nama' => 'Kabupaten Labuhanbatu Selatan']);
        Xkabupaten::factory()->create(['code' => '1223','nama' => 'Kabupaten Labuhanbatu Utara']);
        Xkabupaten::factory()->create(['code' => '1224','nama' => 'Kabupaten Nias Utara']);
        Xkabupaten::factory()->create(['code' => '1225','nama' => 'Kabupaten Nias Barat']);
        Xkabupaten::factory()->create(['code' => '1271','nama' => 'Kota Medan']);
        Xkabupaten::factory()->create(['code' => '1272','nama' => 'Kota Pematangsiantar']);
        Xkabupaten::factory()->create(['code' => '1273','nama' => 'Kota Sibolga']);
        Xkabupaten::factory()->create(['code' => '1274','nama' => 'Kota Tanjung Balai']);
        Xkabupaten::factory()->create(['code' => '1275','nama' => 'Kota Binjai']);
        Xkabupaten::factory()->create(['code' => '1276','nama' => 'Kota Tebing Tinggi']);
        Xkabupaten::factory()->create(['code' => '1277','nama' => 'Kota Padangsidimpuan']);
        Xkabupaten::factory()->create(['code' => '1278','nama' => 'Kota Gunungsitoli']);
        Xkabupaten::factory()->create(['code' => '1301','nama' => 'Kabupaten Pesisir Selatan']);
        Xkabupaten::factory()->create(['code' => '1302','nama' => 'Kabupaten Solok']);
        Xkabupaten::factory()->create(['code' => '1303','nama' => 'Kabupaten Sijunjung']);
        Xkabupaten::factory()->create(['code' => '1304','nama' => 'Kabupaten Tanah Datar']);
        Xkabupaten::factory()->create(['code' => '1305','nama' => 'Kabupaten Padang Pariaman']);
        Xkabupaten::factory()->create(['code' => '1306','nama' => 'Kabupaten Agam']);
        Xkabupaten::factory()->create(['code' => '1307','nama' => 'Kabupaten Lima Puluh Kota']);
        Xkabupaten::factory()->create(['code' => '1308','nama' => 'Kabupaten Pasaman']);
        Xkabupaten::factory()->create(['code' => '1309','nama' => 'Kabupaten Kepulauan Mentawai']);
        Xkabupaten::factory()->create(['code' => '1310','nama' => 'Kabupaten Dharmasraya']);
        Xkabupaten::factory()->create(['code' => '1311','nama' => 'Kabupaten Solok Selatan']);
        Xkabupaten::factory()->create(['code' => '1312','nama' => 'Kabupaten Pasaman Barat']);
        Xkabupaten::factory()->create(['code' => '1371','nama' => 'Kota Padang']);
        Xkabupaten::factory()->create(['code' => '1372','nama' => 'Kota Solok']);
        Xkabupaten::factory()->create(['code' => '1373','nama' => 'Kota Sawahlunto']);
        Xkabupaten::factory()->create(['code' => '1374','nama' => 'Kota Padang Panjang']);
        Xkabupaten::factory()->create(['code' => '1375','nama' => 'Kota Bukittinggi']);
        Xkabupaten::factory()->create(['code' => '1376','nama' => 'Kota Payakumbuh']);
        Xkabupaten::factory()->create(['code' => '1377','nama' => 'Kota Pariaman']);
        Xkabupaten::factory()->create(['code' => '1401','nama' => 'Kabupaten Kampar']);
        Xkabupaten::factory()->create(['code' => '1402','nama' => 'Kabupaten Indragiri Hulu']);
        Xkabupaten::factory()->create(['code' => '1403','nama' => 'Kabupaten Bengkalis']);
        Xkabupaten::factory()->create(['code' => '1404','nama' => 'Kabupaten Indragiri Hilir']);
        Xkabupaten::factory()->create(['code' => '1405','nama' => 'Kabupaten Pelalawan']);
        Xkabupaten::factory()->create(['code' => '1406','nama' => 'Kabupaten Rokan Hulu']);
        Xkabupaten::factory()->create(['code' => '1407','nama' => 'Kabupaten Rokan Hilir']);
        Xkabupaten::factory()->create(['code' => '1408','nama' => 'Kabupaten Siak']);
        Xkabupaten::factory()->create(['code' => '1409','nama' => 'Kabupaten Kuantan Singingi']);
        Xkabupaten::factory()->create(['code' => '1410','nama' => 'Kabupaten Kepulauan Meranti']);
        Xkabupaten::factory()->create(['code' => '1471','nama' => 'Kota Pekanbaru']);
        Xkabupaten::factory()->create(['code' => '1472','nama' => 'Kota Dumai']);
        Xkabupaten::factory()->create(['code' => '1501','nama' => 'Kabupaten Kerinci']);
        Xkabupaten::factory()->create(['code' => '1502','nama' => 'Kabupaten Merangin']);
        Xkabupaten::factory()->create(['code' => '1503','nama' => 'Kabupaten Sarolangun']);
        Xkabupaten::factory()->create(['code' => '1504','nama' => 'Kabupaten Batanghari']);
        Xkabupaten::factory()->create(['code' => '1505','nama' => 'Kabupaten Muaro Jambi']);
        Xkabupaten::factory()->create(['code' => '1506','nama' => 'Kabupaten Tanjung Jabung Barat']);
        Xkabupaten::factory()->create(['code' => '1507','nama' => 'Kabupaten Tanjung Jabung Timur']);
        Xkabupaten::factory()->create(['code' => '1508','nama' => 'Kabupaten Bungo']);
        Xkabupaten::factory()->create(['code' => '1509','nama' => 'Kabupaten Tebo']);
        Xkabupaten::factory()->create(['code' => '1571','nama' => 'Kota Jambi']);
        Xkabupaten::factory()->create(['code' => '1572','nama' => 'Kota Sungai Penuh']);
        Xkabupaten::factory()->create(['code' => '1601','nama' => 'Kabupaten Ogan Komering Ulu']);
        Xkabupaten::factory()->create(['code' => '1602','nama' => 'Kabupaten Ogan Komering Ilir']);
        Xkabupaten::factory()->create(['code' => '1603','nama' => 'Kabupaten Muara Enim']);
        Xkabupaten::factory()->create(['code' => '1604','nama' => 'Kabupaten Lahat']);
        Xkabupaten::factory()->create(['code' => '1605','nama' => 'Kabupaten Musi Rawas']);
        Xkabupaten::factory()->create(['code' => '1606','nama' => 'Kabupaten Musi Banyuasin']);
        Xkabupaten::factory()->create(['code' => '1607','nama' => 'Kabupaten Banyuasin']);
        Xkabupaten::factory()->create(['code' => '1608','nama' => 'Kabupaten Ogan Komering Ulu Timur']);
        Xkabupaten::factory()->create(['code' => '1609','nama' => 'Kabupaten Ogan Komering Ulu Selatan']);
        Xkabupaten::factory()->create(['code' => '1610','nama' => 'Kabupaten Ogan Ilir']);
        Xkabupaten::factory()->create(['code' => '1611','nama' => 'Kabupaten Empat Lawang']);
        Xkabupaten::factory()->create(['code' => '1612','nama' => 'Kabupaten Penukal Abab Lematang Ilir']);
        Xkabupaten::factory()->create(['code' => '1613','nama' => 'Kabupaten Musi Rawas Utara']);
        Xkabupaten::factory()->create(['code' => '1671','nama' => 'Kota Palembang']);
        Xkabupaten::factory()->create(['code' => '1672','nama' => 'Kota Pagar Alam']);
        Xkabupaten::factory()->create(['code' => '1673','nama' => 'Kota Lubuk Linggau']);
        Xkabupaten::factory()->create(['code' => '1674','nama' => 'Kota Prabumulih']);
        Xkabupaten::factory()->create(['code' => '1701','nama' => 'Kabupaten Bengkulu Selatan']);
        Xkabupaten::factory()->create(['code' => '1702','nama' => 'Kabupaten Rejang Lebong']);
        Xkabupaten::factory()->create(['code' => '1703','nama' => 'Kabupaten Bengkulu Utara']);
        Xkabupaten::factory()->create(['code' => '1704','nama' => 'Kabupaten Kaur']);
        Xkabupaten::factory()->create(['code' => '1705','nama' => 'Kabupaten Seluma']);
        Xkabupaten::factory()->create(['code' => '1706','nama' => 'Kabupaten Muko Muko']);
        Xkabupaten::factory()->create(['code' => '1707','nama' => 'Kabupaten Lebong']);
        Xkabupaten::factory()->create(['code' => '1708','nama' => 'Kabupaten Kepahiang']);
        Xkabupaten::factory()->create(['code' => '1709','nama' => 'Kabupaten Bengkulu Tengah']);
        Xkabupaten::factory()->create(['code' => '1771','nama' => 'Kota Bengkulu']);
        Xkabupaten::factory()->create(['code' => '1801','nama' => 'Kabupaten Lampung Selatan']);
        Xkabupaten::factory()->create(['code' => '1802','nama' => 'Kabupaten Lampung Tengah']);
        Xkabupaten::factory()->create(['code' => '1803','nama' => 'Kabupaten Lampung Utara']);
        Xkabupaten::factory()->create(['code' => '1804','nama' => 'Kabupaten Lampung Barat']);
        Xkabupaten::factory()->create(['code' => '1805','nama' => 'Kabupaten Tulang Bawang']);
        Xkabupaten::factory()->create(['code' => '1806','nama' => 'Kabupaten Tanggamus']);
        Xkabupaten::factory()->create(['code' => '1807','nama' => 'Kabupaten Lampung Timur']);
        Xkabupaten::factory()->create(['code' => '1808','nama' => 'Kabupaten Way Kanan']);
        Xkabupaten::factory()->create(['code' => '1809','nama' => 'Kabupaten Pesawaran']);
        Xkabupaten::factory()->create(['code' => '1810','nama' => 'Kabupaten Pringsewu']);
        Xkabupaten::factory()->create(['code' => '1811','nama' => 'Kabupaten Mesuji']);
        Xkabupaten::factory()->create(['code' => '1812','nama' => 'Kabupaten Tulang Bawang Barat']);
        Xkabupaten::factory()->create(['code' => '1813','nama' => 'Kabupaten Pesisir Barat']);
        Xkabupaten::factory()->create(['code' => '1871','nama' => 'Kota Bandar Lampung']);
        Xkabupaten::factory()->create(['code' => '1872','nama' => 'Kota Metro']);
        Xkabupaten::factory()->create(['code' => '1901','nama' => 'Kabupaten Bangka']);
        Xkabupaten::factory()->create(['code' => '1902','nama' => 'Kabupaten Belitung']);
        Xkabupaten::factory()->create(['code' => '1903','nama' => 'Kabupaten Bangka Selatan']);
        Xkabupaten::factory()->create(['code' => '1904','nama' => 'Kabupaten Bangka Tengah']);
        Xkabupaten::factory()->create(['code' => '1905','nama' => 'Kabupaten Bangka Barat']);
        Xkabupaten::factory()->create(['code' => '1906','nama' => 'Kabupaten Belitung Timur']);
        Xkabupaten::factory()->create(['code' => '1971','nama' => 'Kota Pangkal Pinang']);
        Xkabupaten::factory()->create(['code' => '2101','nama' => 'Kabupaten Bintan']);
        Xkabupaten::factory()->create(['code' => '2102','nama' => 'Kabupaten Karimun']);
        Xkabupaten::factory()->create(['code' => '2103','nama' => 'Kabupaten Natuna']);
        Xkabupaten::factory()->create(['code' => '2104','nama' => 'Kabupaten Lingga']);
        Xkabupaten::factory()->create(['code' => '2105','nama' => 'Kabupaten Kepulauan Anambas']);
        Xkabupaten::factory()->create(['code' => '2171','nama' => 'Kota Batam']);
        Xkabupaten::factory()->create(['code' => '2172','nama' => 'Kota Tanjung Pinang']);
        Xkabupaten::factory()->create(['code' => '3101','nama' => 'Kabupaten Administrasi Kepulauan Seribu']);
        Xkabupaten::factory()->create(['code' => '3171','nama' => 'Kota Administrasi Jakarta Pusat']);
        Xkabupaten::factory()->create(['code' => '3172','nama' => 'Kota Administrasi Jakarta Utara']);
        Xkabupaten::factory()->create(['code' => '3173','nama' => 'Kota Administrasi Jakarta Barat']);
        Xkabupaten::factory()->create(['code' => '3174','nama' => 'Kota Administrasi Jakarta Selatan']);
        Xkabupaten::factory()->create(['code' => '3175','nama' => 'Kota Administrasi Jakarta Timur']);
        Xkabupaten::factory()->create(['code' => '3201','nama' => 'Kabupaten Bogor']);
        Xkabupaten::factory()->create(['code' => '3202','nama' => 'Kabupaten Sukabumi']);
        Xkabupaten::factory()->create(['code' => '3203','nama' => 'Kabupaten Cianjur']);
        Xkabupaten::factory()->create(['code' => '3204','nama' => 'Kabupaten Bandung']);
        Xkabupaten::factory()->create(['code' => '3205','nama' => 'Kabupaten Garut']);
        Xkabupaten::factory()->create(['code' => '3206','nama' => 'Kabupaten Tasikmalaya']);
        Xkabupaten::factory()->create(['code' => '3207','nama' => 'Kabupaten Ciamis']);
        Xkabupaten::factory()->create(['code' => '3208','nama' => 'Kabupaten Kuningan']);
        Xkabupaten::factory()->create(['code' => '3209','nama' => 'Kabupaten Cirebon']);
        Xkabupaten::factory()->create(['code' => '3210','nama' => 'Kabupaten Majalengka']);
        Xkabupaten::factory()->create(['code' => '3211','nama' => 'Kabupaten Sumedang']);
        Xkabupaten::factory()->create(['code' => '3212','nama' => 'Kabupaten Indramayu']);
        Xkabupaten::factory()->create(['code' => '3213','nama' => 'Kabupaten Subang']);
        Xkabupaten::factory()->create(['code' => '3214','nama' => 'Kabupaten Purwakarta']);
        Xkabupaten::factory()->create(['code' => '3215','nama' => 'Kabupaten Karawang']);
        Xkabupaten::factory()->create(['code' => '3216','nama' => 'Kabupaten Bekasi']);
        Xkabupaten::factory()->create(['code' => '3217','nama' => 'Kabupaten Bandung Barat']);
        Xkabupaten::factory()->create(['code' => '3218','nama' => 'Kabupaten Pangandaran']);
        Xkabupaten::factory()->create(['code' => '3271','nama' => 'Kota Bogor']);
        Xkabupaten::factory()->create(['code' => '3272','nama' => 'Kota Sukabumi']);
        Xkabupaten::factory()->create(['code' => '3273','nama' => 'Kota Bandung']);
        Xkabupaten::factory()->create(['code' => '3274','nama' => 'Kota Cirebon']);
        Xkabupaten::factory()->create(['code' => '3275','nama' => 'Kota Bekasi']);
        Xkabupaten::factory()->create(['code' => '3276','nama' => 'Kota Depok']);
        Xkabupaten::factory()->create(['code' => '3277','nama' => 'Kota Cimahi']);
        Xkabupaten::factory()->create(['code' => '3278','nama' => 'Kota Tasikmalaya']);
        Xkabupaten::factory()->create(['code' => '3279','nama' => 'Kota Banjar']);
        Xkabupaten::factory()->create(['code' => '3301','nama' => 'Kabupaten Cilacap']);
        Xkabupaten::factory()->create(['code' => '3302','nama' => 'Kabupaten Banyumas']);
        Xkabupaten::factory()->create(['code' => '3303','nama' => 'Kabupaten Purbalingga']);
        Xkabupaten::factory()->create(['code' => '3304','nama' => 'Kabupaten Banjarnegara']);
        Xkabupaten::factory()->create(['code' => '3305','nama' => 'Kabupaten Kebumen']);
        Xkabupaten::factory()->create(['code' => '3306','nama' => 'Kabupaten Purworejo']);
        Xkabupaten::factory()->create(['code' => '3307','nama' => 'Kabupaten Wonosobo']);
        Xkabupaten::factory()->create(['code' => '3308','nama' => 'Kabupaten Magelang']);
        Xkabupaten::factory()->create(['code' => '3309','nama' => 'Kabupaten Boyolali']);
        Xkabupaten::factory()->create(['code' => '3310','nama' => 'Kabupaten Klaten']);
        Xkabupaten::factory()->create(['code' => '3311','nama' => 'Kabupaten Sukoharjo']);
        Xkabupaten::factory()->create(['code' => '3312','nama' => 'Kabupaten Wonogiri']);
        Xkabupaten::factory()->create(['code' => '3313','nama' => 'Kabupaten Karanganyar']);
        Xkabupaten::factory()->create(['code' => '3314','nama' => 'Kabupaten Sragen']);
        Xkabupaten::factory()->create(['code' => '3315','nama' => 'Kabupaten Grobogan']);
        Xkabupaten::factory()->create(['code' => '3316','nama' => 'Kabupaten Blora']);
        Xkabupaten::factory()->create(['code' => '3317','nama' => 'Kabupaten Rembang']);
        Xkabupaten::factory()->create(['code' => '3318','nama' => 'Kabupaten Pati']);
        Xkabupaten::factory()->create(['code' => '3319','nama' => 'Kabupaten Kudus']);
        Xkabupaten::factory()->create(['code' => '3320','nama' => 'Kabupaten Jepara']);
        Xkabupaten::factory()->create(['code' => '3321','nama' => 'Kabupaten Demak']);
        Xkabupaten::factory()->create(['code' => '3322','nama' => 'Kabupaten Semarang']);
        Xkabupaten::factory()->create(['code' => '3323','nama' => 'Kabupaten Temanggung']);
        Xkabupaten::factory()->create(['code' => '3324','nama' => 'Kabupaten Kendal']);
        Xkabupaten::factory()->create(['code' => '3325','nama' => 'Kabupaten Batang']);
        Xkabupaten::factory()->create(['code' => '3326','nama' => 'Kabupaten Pekalongan']);
        Xkabupaten::factory()->create(['code' => '3327','nama' => 'Kabupaten Pemalang']);
        Xkabupaten::factory()->create(['code' => '3328','nama' => 'Kabupaten Tegal']);
        Xkabupaten::factory()->create(['code' => '3329','nama' => 'Kabupaten Brebes']);
        Xkabupaten::factory()->create(['code' => '3371','nama' => 'Kota Magelang']);
        Xkabupaten::factory()->create(['code' => '3372','nama' => 'Kota Surakarta']);
        Xkabupaten::factory()->create(['code' => '3373','nama' => 'Kota Salatiga']);
        Xkabupaten::factory()->create(['code' => '3374','nama' => 'Kota Semarang']);
        Xkabupaten::factory()->create(['code' => '3375','nama' => 'Kota Pekalongan']);
        Xkabupaten::factory()->create(['code' => '3376','nama' => 'Kota Tegal']);
        Xkabupaten::factory()->create(['code' => '3401','nama' => 'Kabupaten Kulon Progo']);
        Xkabupaten::factory()->create(['code' => '3402','nama' => 'Kabupaten Bantul']);
        Xkabupaten::factory()->create(['code' => '3403','nama' => 'Kabupaten Gunungkidul']);
        Xkabupaten::factory()->create(['code' => '3404','nama' => 'Kabupaten Sleman']);
        Xkabupaten::factory()->create(['code' => '3471','nama' => 'Kota Yogyakarta']);
        Xkabupaten::factory()->create(['code' => '3501','nama' => 'Kabupaten Pacitan']);
        Xkabupaten::factory()->create(['code' => '3502','nama' => 'Kabupaten Ponorogo']);
        Xkabupaten::factory()->create(['code' => '3503','nama' => 'Kabupaten Trenggalek']);
        Xkabupaten::factory()->create(['code' => '3504','nama' => 'Kabupaten Tulungagung']);
        Xkabupaten::factory()->create(['code' => '3505','nama' => 'Kabupaten Blitar']);
        Xkabupaten::factory()->create(['code' => '3506','nama' => 'Kabupaten Kediri']);
        Xkabupaten::factory()->create(['code' => '3507','nama' => 'Kabupaten Malang']);
        Xkabupaten::factory()->create(['code' => '3508','nama' => 'Kabupaten Lumajang']);
        Xkabupaten::factory()->create(['code' => '3509','nama' => 'Kabupaten Jember']);
        Xkabupaten::factory()->create(['code' => '3510','nama' => 'Kabupaten Banyuwangi']);
        Xkabupaten::factory()->create(['code' => '3511','nama' => 'Kabupaten Bondowoso']);
        Xkabupaten::factory()->create(['code' => '3512','nama' => 'Kabupaten Situbondo']);
        Xkabupaten::factory()->create(['code' => '3513','nama' => 'Kabupaten Probolinggo']);
        Xkabupaten::factory()->create(['code' => '3514','nama' => 'Kabupaten Pasuruan']);
        Xkabupaten::factory()->create(['code' => '3515','nama' => 'Kabupaten Sidoarjo']);
        Xkabupaten::factory()->create(['code' => '3516','nama' => 'Kabupaten Mojokerto']);
        Xkabupaten::factory()->create(['code' => '3517','nama' => 'Kabupaten Jombang']);
        Xkabupaten::factory()->create(['code' => '3518','nama' => 'Kabupaten Nganjuk']);
        Xkabupaten::factory()->create(['code' => '3519','nama' => 'Kabupaten Madiun']);
        Xkabupaten::factory()->create(['code' => '3520','nama' => 'Kabupaten Magetan']);
        Xkabupaten::factory()->create(['code' => '3521','nama' => 'Kabupaten Ngawi']);
        Xkabupaten::factory()->create(['code' => '3522','nama' => 'Kabupaten Bojonegoro']);
        Xkabupaten::factory()->create(['code' => '3523','nama' => 'Kabupaten Tuban']);
        Xkabupaten::factory()->create(['code' => '3524','nama' => 'Kabupaten Lamongan']);
        Xkabupaten::factory()->create(['code' => '3525','nama' => 'Kabupaten Gresik']);
        Xkabupaten::factory()->create(['code' => '3526','nama' => 'Kabupaten Bangkalan']);
        Xkabupaten::factory()->create(['code' => '3527','nama' => 'Kabupaten Sampang']);
        Xkabupaten::factory()->create(['code' => '3528','nama' => 'Kabupaten Pamekasan']);
        Xkabupaten::factory()->create(['code' => '3529','nama' => 'Kabupaten Sumenep']);
        Xkabupaten::factory()->create(['code' => '3571','nama' => 'Kota Kediri']);
        Xkabupaten::factory()->create(['code' => '3572','nama' => 'Kota Blitar']);
        Xkabupaten::factory()->create(['code' => '3573','nama' => 'Kota Malang']);
        Xkabupaten::factory()->create(['code' => '3574','nama' => 'Kota Probolinggo']);
        Xkabupaten::factory()->create(['code' => '3575','nama' => 'Kota Pasuruan']);
        Xkabupaten::factory()->create(['code' => '3576','nama' => 'Kota Mojokerto']);
        Xkabupaten::factory()->create(['code' => '3577','nama' => 'Kota Madiun']);
        Xkabupaten::factory()->create(['code' => '3578','nama' => 'Kota Surabaya']);
        Xkabupaten::factory()->create(['code' => '3579','nama' => 'Kota Batu']);
        Xkabupaten::factory()->create(['code' => '3601','nama' => 'Kabupaten Pandeglang']);
        Xkabupaten::factory()->create(['code' => '3602','nama' => 'Kabupaten Lebak']);
        Xkabupaten::factory()->create(['code' => '3603','nama' => 'Kabupaten Tangerang']);
        Xkabupaten::factory()->create(['code' => '3604','nama' => 'Kabupaten Serang']);
        Xkabupaten::factory()->create(['code' => '3671','nama' => 'Kota Tangerang']);
        Xkabupaten::factory()->create(['code' => '3672','nama' => 'Kota Cilegon']);
        Xkabupaten::factory()->create(['code' => '3673','nama' => 'Kota Serang']);
        Xkabupaten::factory()->create(['code' => '3674','nama' => 'Kota Tangerang Selatan']);
        Xkabupaten::factory()->create(['code' => '5101','nama' => 'Kabupaten Jembrana']);
        Xkabupaten::factory()->create(['code' => '5102','nama' => 'Kabupaten Tabanan']);
        Xkabupaten::factory()->create(['code' => '5103','nama' => 'Kabupaten Badung']);
        Xkabupaten::factory()->create(['code' => '5104','nama' => 'Kabupaten Gianyar']);
        Xkabupaten::factory()->create(['code' => '5105','nama' => 'Kabupaten Klungkung']);
        Xkabupaten::factory()->create(['code' => '5106','nama' => 'Kabupaten Bangli']);
        Xkabupaten::factory()->create(['code' => '5107','nama' => 'Kabupaten Karangasem']);
        Xkabupaten::factory()->create(['code' => '5108','nama' => 'Kabupaten Buleleng']);
        Xkabupaten::factory()->create(['code' => '5171','nama' => 'Kota Denpasar']);
        Xkabupaten::factory()->create(['code' => '5201','nama' => 'Kabupaten Lombok Barat']);
        Xkabupaten::factory()->create(['code' => '5202','nama' => 'Kabupaten Lombok Tengah']);
        Xkabupaten::factory()->create(['code' => '5203','nama' => 'Kabupaten Lombok Timur']);
        Xkabupaten::factory()->create(['code' => '5204','nama' => 'Kabupaten Sumbawa']);
        Xkabupaten::factory()->create(['code' => '5205','nama' => 'Kabupaten Dompu']);
        Xkabupaten::factory()->create(['code' => '5206','nama' => 'Kabupaten Bima']);
        Xkabupaten::factory()->create(['code' => '5207','nama' => 'Kabupaten Sumbawa Barat']);
        Xkabupaten::factory()->create(['code' => '5208','nama' => 'Kabupaten Lombok Utara']);
        Xkabupaten::factory()->create(['code' => '5271','nama' => 'Kota Mataram']);
        Xkabupaten::factory()->create(['code' => '5272','nama' => 'Kota Bima']);
        Xkabupaten::factory()->create(['code' => '5301','nama' => 'Kabupaten Kupang']);
        Xkabupaten::factory()->create(['code' => '5302','nama' => 'Kabupaten Timor Tengah Selatan']);
        Xkabupaten::factory()->create(['code' => '5303','nama' => 'Kabupaten Timor Tengah Utara']);
        Xkabupaten::factory()->create(['code' => '5304','nama' => 'Kabupaten Belu']);
        Xkabupaten::factory()->create(['code' => '5305','nama' => 'Kabupaten Alor']);
        Xkabupaten::factory()->create(['code' => '5306','nama' => 'Kabupaten Flores Timur']);
        Xkabupaten::factory()->create(['code' => '5307','nama' => 'Kabupaten Sikka']);
        Xkabupaten::factory()->create(['code' => '5308','nama' => 'Kabupaten Ende']);
        Xkabupaten::factory()->create(['code' => '5309','nama' => 'Kabupaten Ngada']);
        Xkabupaten::factory()->create(['code' => '5310','nama' => 'Kabupaten Manggarai']);
        Xkabupaten::factory()->create(['code' => '5311','nama' => 'Kabupaten Sumba Timur']);
        Xkabupaten::factory()->create(['code' => '5312','nama' => 'Kabupaten Sumba Barat']);
        Xkabupaten::factory()->create(['code' => '5313','nama' => 'Kabupaten Lembata']);
        Xkabupaten::factory()->create(['code' => '5314','nama' => 'Kabupaten Rote Ndao']);
        Xkabupaten::factory()->create(['code' => '5315','nama' => 'Kabupaten Manggarai Barat']);
        Xkabupaten::factory()->create(['code' => '5316','nama' => 'Kabupaten Nagekeo']);
        Xkabupaten::factory()->create(['code' => '5317','nama' => 'Kabupaten Sumba Tengah']);
        Xkabupaten::factory()->create(['code' => '5318','nama' => 'Kabupaten Sumba Barat Daya']);
        Xkabupaten::factory()->create(['code' => '5319','nama' => 'Kabupaten Manggarai Timur']);
        Xkabupaten::factory()->create(['code' => '5320','nama' => 'Kabupaten Sabu Raijua']);
        Xkabupaten::factory()->create(['code' => '5321','nama' => 'Kabupaten Malaka']);
        Xkabupaten::factory()->create(['code' => '5371','nama' => 'Kota Kupang']);
        Xkabupaten::factory()->create(['code' => '6101','nama' => 'Kabupaten Sambas']);
        Xkabupaten::factory()->create(['code' => '6102','nama' => 'Kabupaten Mempawah']);
        Xkabupaten::factory()->create(['code' => '6103','nama' => 'Kabupaten Sanggau']);
        Xkabupaten::factory()->create(['code' => '6104','nama' => 'Kabupaten Ketapang']);
        Xkabupaten::factory()->create(['code' => '6105','nama' => 'Kabupaten Sintang']);
        Xkabupaten::factory()->create(['code' => '6106','nama' => 'Kabupaten Kapuas Hulu']);
        Xkabupaten::factory()->create(['code' => '6107','nama' => 'Kabupaten Bengkayang']);
        Xkabupaten::factory()->create(['code' => '6108','nama' => 'Kabupaten Landak']);
        Xkabupaten::factory()->create(['code' => '6109','nama' => 'Kabupaten Sekadau']);
        Xkabupaten::factory()->create(['code' => '6110','nama' => 'Kabupaten Melawi']);
        Xkabupaten::factory()->create(['code' => '6111','nama' => 'Kabupaten Kayong Utara']);
        Xkabupaten::factory()->create(['code' => '6112','nama' => 'Kabupaten Kubu Raya']);
        Xkabupaten::factory()->create(['code' => '6171','nama' => 'Kota Pontianak']);
        Xkabupaten::factory()->create(['code' => '6172','nama' => 'Kota Singkawang']);
        Xkabupaten::factory()->create(['code' => '6201','nama' => 'Kabupaten Kotawaringin Barat']);
        Xkabupaten::factory()->create(['code' => '6202','nama' => 'Kabupaten Kotawaringin Timur']);
        Xkabupaten::factory()->create(['code' => '6203','nama' => 'Kabupaten Kapuas']);
        Xkabupaten::factory()->create(['code' => '6204','nama' => 'Kabupaten Barito Selatan']);
        Xkabupaten::factory()->create(['code' => '6205','nama' => 'Kabupaten Barito Utara']);
        Xkabupaten::factory()->create(['code' => '6206','nama' => 'Kabupaten Katingan']);
        Xkabupaten::factory()->create(['code' => '6207','nama' => 'Kabupaten Seruyan']);
        Xkabupaten::factory()->create(['code' => '6208','nama' => 'Kabupaten Sukamara']);
        Xkabupaten::factory()->create(['code' => '6209','nama' => 'Kabupaten Lamandau']);
        Xkabupaten::factory()->create(['code' => '6210','nama' => 'Kabupaten Gunung Mas']);
        Xkabupaten::factory()->create(['code' => '6211','nama' => 'Kabupaten Pulang Pisau']);
        Xkabupaten::factory()->create(['code' => '6212','nama' => 'Kabupaten Murung Raya']);
        Xkabupaten::factory()->create(['code' => '6213','nama' => 'Kabupaten Barito Timur']);
        Xkabupaten::factory()->create(['code' => '6271','nama' => 'Kota Palangkaraya']);
        Xkabupaten::factory()->create(['code' => '6301','nama' => 'Kabupaten Tanah Laut']);
        Xkabupaten::factory()->create(['code' => '6302','nama' => 'Kabupaten Kotabaru']);
        Xkabupaten::factory()->create(['code' => '6303','nama' => 'Kabupaten Banjar']);
        Xkabupaten::factory()->create(['code' => '6304','nama' => 'Kabupaten Barito Kuala']);
        Xkabupaten::factory()->create(['code' => '6305','nama' => 'Kabupaten Tapin']);
        Xkabupaten::factory()->create(['code' => '6306','nama' => 'Kabupaten Hulu Sungai Selatan']);
        Xkabupaten::factory()->create(['code' => '6307','nama' => 'Kabupaten Hulu Sungai Tengah']);
        Xkabupaten::factory()->create(['code' => '6308','nama' => 'Kabupaten Hulu Sungai Utara']);
        Xkabupaten::factory()->create(['code' => '6309','nama' => 'Kabupaten Tabalong']);
        Xkabupaten::factory()->create(['code' => '6310','nama' => 'Kabupaten Tanah Bumbu']);
        Xkabupaten::factory()->create(['code' => '6311','nama' => 'Kabupaten Balangan']);
        Xkabupaten::factory()->create(['code' => '6371','nama' => 'Kota Banjarmasin']);
        Xkabupaten::factory()->create(['code' => '6372','nama' => 'Kota Banjarbaru']);
        Xkabupaten::factory()->create(['code' => '6401','nama' => 'Kabupaten Paser']);
        Xkabupaten::factory()->create(['code' => '6402','nama' => 'Kabupaten Kutai Kartanegara']);
        Xkabupaten::factory()->create(['code' => '6403','nama' => 'Kabupaten Berau']);
        Xkabupaten::factory()->create(['code' => '6407','nama' => 'Kabupaten Kutai Barat']);
        Xkabupaten::factory()->create(['code' => '6408','nama' => 'Kabupaten Kutai Timur']);
        Xkabupaten::factory()->create(['code' => '6409','nama' => 'Kabupaten Penajam Paser Utara']);
        Xkabupaten::factory()->create(['code' => '6411','nama' => 'Kabupaten Mahakam Ulu']);
        Xkabupaten::factory()->create(['code' => '6471','nama' => 'Kota Balikpapan']);
        Xkabupaten::factory()->create(['code' => '6472','nama' => 'Kota Samarinda']);
        Xkabupaten::factory()->create(['code' => '6474','nama' => 'Kota Bontang']);
        Xkabupaten::factory()->create(['code' => '6501','nama' => 'Kabupaten Bulungan']);
        Xkabupaten::factory()->create(['code' => '6502','nama' => 'Kabupaten Malinau']);
        Xkabupaten::factory()->create(['code' => '6503','nama' => 'Kabupaten Nunukan']);
        Xkabupaten::factory()->create(['code' => '6504','nama' => 'Kabupaten Tana Tidung']);
        Xkabupaten::factory()->create(['code' => '6571','nama' => 'Kota Tarakan']);
        Xkabupaten::factory()->create(['code' => '7101','nama' => 'Kabupaten Bolaang Mongondow']);
        Xkabupaten::factory()->create(['code' => '7102','nama' => 'Kabupaten Minahasa']);
        Xkabupaten::factory()->create(['code' => '7103','nama' => 'Kabupaten Kepulauan Sangihe']);
        Xkabupaten::factory()->create(['code' => '7104','nama' => 'Kabupaten Kepulauan Talaud']);
        Xkabupaten::factory()->create(['code' => '7105','nama' => 'Kabupaten Minahasa Selatan']);
        Xkabupaten::factory()->create(['code' => '7106','nama' => 'Kabupaten Minahasa Utara']);
        Xkabupaten::factory()->create(['code' => '7107','nama' => 'Kabupaten Minahasa Tenggara']);
        Xkabupaten::factory()->create(['code' => '7108','nama' => 'Kabupaten Bolaang Mongondow Utara']);
        Xkabupaten::factory()->create(['code' => '7109','nama' => 'Kabupaten Kepulauan Siau Tagulandang Biaro']);
        Xkabupaten::factory()->create(['code' => '7110','nama' => 'Kabupaten Bolaang Mongondow Timur']);
        Xkabupaten::factory()->create(['code' => '7111','nama' => 'Kabupaten Bolaang Mongondow Selatan']);
        Xkabupaten::factory()->create(['code' => '7171','nama' => 'Kota Manado']);
        Xkabupaten::factory()->create(['code' => '7172','nama' => 'Kota Bitung']);
        Xkabupaten::factory()->create(['code' => '7173','nama' => 'Kota Tomohon']);
        Xkabupaten::factory()->create(['code' => '7174','nama' => 'Kota Kotamobagu']);
        Xkabupaten::factory()->create(['code' => '7201','nama' => 'Kabupaten Banggai']);
        Xkabupaten::factory()->create(['code' => '7202','nama' => 'Kabupaten Poso']);
        Xkabupaten::factory()->create(['code' => '7203','nama' => 'Kabupaten Donggala']);
        Xkabupaten::factory()->create(['code' => '7204','nama' => 'Kabupaten Toli Toli']);
        Xkabupaten::factory()->create(['code' => '7205','nama' => 'Kabupaten Buol']);
        Xkabupaten::factory()->create(['code' => '7206','nama' => 'Kabupaten Morowali']);
        Xkabupaten::factory()->create(['code' => '7207','nama' => 'Kabupaten Banggai Kepulauan']);
        Xkabupaten::factory()->create(['code' => '7208','nama' => 'Kabupaten Parigi Moutong']);
        Xkabupaten::factory()->create(['code' => '7209','nama' => 'Kabupaten Tojo Una Una']);
        Xkabupaten::factory()->create(['code' => '7210','nama' => 'Kabupaten Sigi']);
        Xkabupaten::factory()->create(['code' => '7211','nama' => 'Kabupaten Banggai Laut']);
        Xkabupaten::factory()->create(['code' => '7212','nama' => 'Kabupaten Morowali Utara']);
        Xkabupaten::factory()->create(['code' => '7271','nama' => 'Kota Palu']);
        Xkabupaten::factory()->create(['code' => '7301','nama' => 'Kabupaten Kepulauan Selayar']);
        Xkabupaten::factory()->create(['code' => '7302','nama' => 'Kabupaten Bulukumba']);
        Xkabupaten::factory()->create(['code' => '7303','nama' => 'Kabupaten Bantaeng']);
        Xkabupaten::factory()->create(['code' => '7304','nama' => 'Kabupaten Jeneponto']);
        Xkabupaten::factory()->create(['code' => '7305','nama' => 'Kabupaten Takalar']);
        Xkabupaten::factory()->create(['code' => '7306','nama' => 'Kabupaten Gowa']);
        Xkabupaten::factory()->create(['code' => '7307','nama' => 'Kabupaten Sinjai']);
        Xkabupaten::factory()->create(['code' => '7308','nama' => 'Kabupaten Bone']);
        Xkabupaten::factory()->create(['code' => '7309','nama' => 'Kabupaten Maros']);
        Xkabupaten::factory()->create(['code' => '7310','nama' => 'Kabupaten Pangkajene Kepulauan']);
        Xkabupaten::factory()->create(['code' => '7311','nama' => 'Kabupaten Barru']);
        Xkabupaten::factory()->create(['code' => '7312','nama' => 'Kabupaten Soppeng']);
        Xkabupaten::factory()->create(['code' => '7313','nama' => 'Kabupaten Wajo']);
        Xkabupaten::factory()->create(['code' => '7314','nama' => 'Kabupaten Sidenreng Rappang']);
        Xkabupaten::factory()->create(['code' => '7315','nama' => 'Kabupaten Pinrang']);
        Xkabupaten::factory()->create(['code' => '7316','nama' => 'Kabupaten Enrekang']);
        Xkabupaten::factory()->create(['code' => '7317','nama' => 'Kabupaten Luwu']);
        Xkabupaten::factory()->create(['code' => '7318','nama' => 'Kabupaten Tana Toraja']);
        Xkabupaten::factory()->create(['code' => '7322','nama' => 'Kabupaten Luwu Utara']);
        Xkabupaten::factory()->create(['code' => '7324','nama' => 'Kabupaten Luwu Timur']);
        Xkabupaten::factory()->create(['code' => '7326','nama' => 'Kabupaten Toraja Utara']);
        Xkabupaten::factory()->create(['code' => '7371','nama' => 'Kota Makassar']);
        Xkabupaten::factory()->create(['code' => '7372','nama' => 'Kota Pare Pare']);
        Xkabupaten::factory()->create(['code' => '7373','nama' => 'Kota Palopo']);
        Xkabupaten::factory()->create(['code' => '7401','nama' => 'Kabupaten Kolaka']);
        Xkabupaten::factory()->create(['code' => '7402','nama' => 'Kabupaten Konawe']);
        Xkabupaten::factory()->create(['code' => '7403','nama' => 'Kabupaten Muna']);
        Xkabupaten::factory()->create(['code' => '7404','nama' => 'Kabupaten Buton']);
        Xkabupaten::factory()->create(['code' => '7405','nama' => 'Kabupaten Konawe Selatan']);
        Xkabupaten::factory()->create(['code' => '7406','nama' => 'Kabupaten Bombana']);
        Xkabupaten::factory()->create(['code' => '7407','nama' => 'Kabupaten Wakatobi']);
        Xkabupaten::factory()->create(['code' => '7408','nama' => 'Kabupaten Kolaka Utara']);
        Xkabupaten::factory()->create(['code' => '7409','nama' => 'Kabupaten Konawe Utara']);
        Xkabupaten::factory()->create(['code' => '7410','nama' => 'Kabupaten Buton Utara']);
        Xkabupaten::factory()->create(['code' => '7411','nama' => 'Kabupaten Kolaka Timur']);
        Xkabupaten::factory()->create(['code' => '7412','nama' => 'Kabupaten Konawe Kepulauan']);
        Xkabupaten::factory()->create(['code' => '7413','nama' => 'Kabupaten Muna Barat']);
        Xkabupaten::factory()->create(['code' => '7414','nama' => 'Kabupaten Buton Tengah']);
        Xkabupaten::factory()->create(['code' => '7415','nama' => 'Kabupaten Buton Selatan']);
        Xkabupaten::factory()->create(['code' => '7471','nama' => 'Kota Kendari']);
        Xkabupaten::factory()->create(['code' => '7472','nama' => 'Kota Bau Bau']);
        Xkabupaten::factory()->create(['code' => '7501','nama' => 'Kabupaten Gorontalo']);
        Xkabupaten::factory()->create(['code' => '7502','nama' => 'Kabupaten Boalemo']);
        Xkabupaten::factory()->create(['code' => '7503','nama' => 'Kabupaten Bone Bolango']);
        Xkabupaten::factory()->create(['code' => '7504','nama' => 'Kabupaten Pahuwato']);
        Xkabupaten::factory()->create(['code' => '7505','nama' => 'Kabupaten Gorontalo Utara']);
        Xkabupaten::factory()->create(['code' => '7571','nama' => 'Kota Gorontalo']);
        Xkabupaten::factory()->create(['code' => '7601','nama' => 'Kabupaten Pasangkayu']);
        Xkabupaten::factory()->create(['code' => '7602','nama' => 'Kabupaten Mamuju']);
        Xkabupaten::factory()->create(['code' => '7603','nama' => 'Kabupaten Mamasa']);
        Xkabupaten::factory()->create(['code' => '7604','nama' => 'Kabupaten Polewali Mandar']);
        Xkabupaten::factory()->create(['code' => '7605','nama' => 'Kabupaten Majene']);
        Xkabupaten::factory()->create(['code' => '7606','nama' => 'Kabupaten Mamuju Tengah']);
        Xkabupaten::factory()->create(['code' => '8101','nama' => 'Kabupaten Maluku Tengah']);
        Xkabupaten::factory()->create(['code' => '8102','nama' => 'Kabupaten Maluku Tenggara']);
        Xkabupaten::factory()->create(['code' => '8103','nama' => 'Kabupaten Kepulauan Tanimbar']);
        Xkabupaten::factory()->create(['code' => '8104','nama' => 'Kabupaten Buru']);
        Xkabupaten::factory()->create(['code' => '8105','nama' => 'Kabupaten Seram Bagian Timur']);
        Xkabupaten::factory()->create(['code' => '8106','nama' => 'Kabupaten Seram Bagian Barat']);
        Xkabupaten::factory()->create(['code' => '8107','nama' => 'Kabupaten Kepulauan Aru']);
        Xkabupaten::factory()->create(['code' => '8108','nama' => 'Kabupaten Maluku Barat Daya']);
        Xkabupaten::factory()->create(['code' => '8109','nama' => 'Kabupaten Buru Selatan']);
        Xkabupaten::factory()->create(['code' => '8171','nama' => 'Kota Ambon']);
        Xkabupaten::factory()->create(['code' => '8172','nama' => 'Kota Tual']);
        Xkabupaten::factory()->create(['code' => '8201','nama' => 'Kabupaten Halmahera Barat']);
        Xkabupaten::factory()->create(['code' => '8202','nama' => 'Kabupaten Halmahera Tengah']);
        Xkabupaten::factory()->create(['code' => '8203','nama' => 'Kabupaten Halmahera Utara']);
        Xkabupaten::factory()->create(['code' => '8204','nama' => 'Kabupaten Halmahera Selatan']);
        Xkabupaten::factory()->create(['code' => '8205','nama' => 'Kabupaten Kepulauan Sula']);
        Xkabupaten::factory()->create(['code' => '8206','nama' => 'Kabupaten Halmahera Timur']);
        Xkabupaten::factory()->create(['code' => '8207','nama' => 'Kabupaten Pulau Morotai']);
        Xkabupaten::factory()->create(['code' => '8208','nama' => 'Kabupaten Pulau Taliabu']);
        Xkabupaten::factory()->create(['code' => '8271','nama' => 'Kota Ternate']);
        Xkabupaten::factory()->create(['code' => '8272','nama' => 'Kota Tidore Kepulauan']);
        Xkabupaten::factory()->create(['code' => '9101','nama' => 'Kabupaten Merauke']);
        Xkabupaten::factory()->create(['code' => '9102','nama' => 'Kabupaten Jayawijaya']);
        Xkabupaten::factory()->create(['code' => '9103','nama' => 'Kabupaten Jayapura']);
        Xkabupaten::factory()->create(['code' => '9104','nama' => 'Kabupaten Nabire']);
        Xkabupaten::factory()->create(['code' => '9105','nama' => 'Kabupaten Kepulauan Yapen']);
        Xkabupaten::factory()->create(['code' => '9106','nama' => 'Kabupaten Biak Numfor']);
        Xkabupaten::factory()->create(['code' => '9107','nama' => 'Kabupaten Puncak Jaya']);
        Xkabupaten::factory()->create(['code' => '9108','nama' => 'Kabupaten Paniai']);
        Xkabupaten::factory()->create(['code' => '9109','nama' => 'Kabupaten Mimika']);
        Xkabupaten::factory()->create(['code' => '9110','nama' => 'Kabupaten Sarmi']);
        Xkabupaten::factory()->create(['code' => '9111','nama' => 'Kabupaten Keerom']);
        Xkabupaten::factory()->create(['code' => '9112','nama' => 'Kabupaten Pegunungan Bintang']);
        Xkabupaten::factory()->create(['code' => '9113','nama' => 'Kabupaten Yahukimo']);
        Xkabupaten::factory()->create(['code' => '9114','nama' => 'Kabupaten Tolikara']);
        Xkabupaten::factory()->create(['code' => '9115','nama' => 'Kabupaten Waropen']);
        Xkabupaten::factory()->create(['code' => '9116','nama' => 'Kabupaten Boven Digoel']);
        Xkabupaten::factory()->create(['code' => '9117','nama' => 'Kabupaten Mappi']);
        Xkabupaten::factory()->create(['code' => '9118','nama' => 'Kabupaten Asmat']);
        Xkabupaten::factory()->create(['code' => '9119','nama' => 'Kabupaten Supiori']);
        Xkabupaten::factory()->create(['code' => '9120','nama' => 'Kabupaten Mamberamo Raya']);
        Xkabupaten::factory()->create(['code' => '9121','nama' => 'Kabupaten Mamberamo Tengah']);
        Xkabupaten::factory()->create(['code' => '9122','nama' => 'Kabupaten Yalimo']);
        Xkabupaten::factory()->create(['code' => '9123','nama' => 'Kabupaten Lanny Jaya']);
        Xkabupaten::factory()->create(['code' => '9124','nama' => 'Kabupaten Nduga']);
        Xkabupaten::factory()->create(['code' => '9125','nama' => 'Kabupaten Puncak']);
        Xkabupaten::factory()->create(['code' => '9126','nama' => 'Kabupaten Dogiyai']);
        Xkabupaten::factory()->create(['code' => '9127','nama' => 'Kabupaten Intan Jaya']);
        Xkabupaten::factory()->create(['code' => '9128','nama' => 'Kabupaten Deiyai']);
        Xkabupaten::factory()->create(['code' => '9171','nama' => 'Kota Jayapura']);
        Xkabupaten::factory()->create(['code' => '9201','nama' => 'Kabupaten Sorong']);
        Xkabupaten::factory()->create(['code' => '9202','nama' => 'Kabupaten Manokwari']);
        Xkabupaten::factory()->create(['code' => '9203','nama' => 'Kabupaten Fak Fak']);
        Xkabupaten::factory()->create(['code' => '9204','nama' => 'Kabupaten Sorong Selatan']);
        Xkabupaten::factory()->create(['code' => '9205','nama' => 'Kabupaten Raja Ampat']);
        Xkabupaten::factory()->create(['code' => '9206','nama' => 'Kabupaten Teluk Bintuni']);
        Xkabupaten::factory()->create(['code' => '9207','nama' => 'Kabupaten Teluk Wondama']);
        Xkabupaten::factory()->create(['code' => '9208','nama' => 'Kabupaten Kaimana']);
        Xkabupaten::factory()->create(['code' => '9209','nama' => 'Kabupaten Tambrauw']);
        Xkabupaten::factory()->create(['code' => '9210','nama' => 'Kabupaten Maybrat']);
        Xkabupaten::factory()->create(['code' => '9211','nama' => 'Kabupaten Manokwari Selatan']);
        Xkabupaten::factory()->create(['code' => '9212','nama' => 'Kabupaten Pegunungan Arfak']);
        Xkabupaten::factory()->create(['code' => '9271','nama' => 'Kota Sorong']);
    }
}
